---
- hosts: localhost
  connection: local 
  become: true
  tasks:
  - name: building docker image
    command: docker build -t jay 
  - name: creating docker image
    command: docker run -d -p 80:80 jay
